---
- hosts: controllers
  remote_user: "{{remote_user}}"
  become_method: sudo
  serial: 1
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: test
    become: yes
    changed_when: test.stdout
  - setup:
  tasks:
  - import_role:
      name: security
    become: yes
    tags: ["prepare","security"]
  - import_role:
      name: "nickjj.docker"
    tags: ["prepare","docker"]
    become: yes
  - import_role:
      name: geerlingguy.nodejs
    become: yes
    tags: ["prepare","node"]
  - import_role:
      name: common
    become: yes
    tags: ["prepare","common"]
  - name: create ~/ipfs-benchmarks
    become: yes
    file:
      path: /home/ubuntu/ipfs-benchmarks
      state: directory
      mode: 0755
      owner: ubuntu
      group: docker
      recurse: yes
  - name: create influxdb and grafana data dirs
    become: yes
    file:
      path: "{{ item.path }}"
      owner: "{{ item.uid | default('ubuntu') }}"
      group: "{{ item.guid | default('docker') }}"
      state: directory
      recurse: yes
      mode: 0755
    with_items:
    - { path: '/data/influxdb' }
    - { path: '/data/grafana', uid: 472, guid: docker }
  - name: copy code
    become: no
    synchronize:
      src: ../../../
      dest: ~/ipfs-benchmarks/
      checksum: yes
      rsync_opts:
        - "--exclude=runner/node_modules"
        - "--exclude=tests/node_modules"
  - import_role:
      name: redeploy
    become: yes
    tags: ["redeploy"]
