version: 2
jobs:
  build:
    working_directory: ~/ipfs
    docker:
      - image: nearform/circleci-node-ansible:1.0.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'

      - restore_cache:
          key: dependency-runner-cache-{{ checksum "runner/package.json" }}
      - run:
          name: npm-install-runner
          command: cd runner && npm install
      - save_cache:
          key: dependency-runner-cache-{{ checksum "runner/package.json" }}
          paths:
            - ./runner/node_modules

      - restore_cache:
          key: dependency-benchmark-cache-{{ checksum "tests/package.json" }}
      - run:
          name: npm-install-benchmarks
          command: cd tests && npm install
      - save_cache:
          key: dependency-benchmark-cache-{{ checksum "tests/package.json" }}
          paths:
            - ./tests/node_modules

      - run:
          name: test-benchmarks
          command: cd tests && NODE_ENV=test npm test
      - run:
          name: test-runner
          command: cd runner && NODE_ENV=test npm test
    deploy:
      - run:
          name: get private key
          command: |
            echo $IPFS_KEY | base64 -d > ~/.ssh/id_rsa_ipfs
            chmod 600 ~/.ssh/id_rsa_ipfs
      - run:
          name: deploy
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False \
            ansible-playbook -i infrastructure/inventory/inventory.yaml \
            infrastructure/playbooks/controller.yaml \
            --skip-tags "prepare"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

