version: 2
jobs:
  build:
    working_directory: ~/ipfs
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./runner/node_modules
            - ./tests/node_modules
      - run:
          name: test
          command: npm test
      # TBD :
      # - run:
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
      # - store_test_results:
      #     path: test-results.xml