---
- name: Install packages based on package.json.
  become: no
  npm:
    path: ~/ipfs-benchmarks/runner
- name: install python docker-compose
  pip:
    name: docker-compose
- name: rebuild / restart
  shell: runProdEnv.sh restart
  args:
    chdir: /home/ubuntu/ipfs-benchmarks/scripts
