---
- name: Install packages based on package.json.
  become: no
  npm:
    path: ~/ipfs-benchmarks/runner
- name: install python docker-compose
  pip:
    name: docker-compose
- name: rebuild / restart
  docker_service:
    project_src: /home/ubuntu/ipfs-benchmarks/infrastructure/deploy
    build: yes
    restarted: true