---
- name: Install packages based on package.json.
  become: no
  npm:
    path: "{{ remote_folder }}"
- name: Ensure Unit file
  template:
    src: runner.service.j2
    dest: /lib/systemd/system/runner.service
    mode: 644
  notify:
    - reload systemctl
- name: Restart runner
  service:
    name: runner.service
    state: restarted
    enabled: yes