version: "3"
services:
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - /data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: benchmarks
  runner:
    build:
      context: ../../
      dockerfile: Dockerfile-runner
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      INFLUX_HOST: influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
     - "3000:3000"
    volumes:
      - /data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    links:
      - influxdb
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    links:
      - grafana:graf
      - runner:run
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
