version: "3"
services:
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - ../../../data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: benchmarks
  runner:
    build:
      context: ../../
      dockerfile: Dockerfile-runner
    depends_on:
      - influxdb
    ports:
      - "9000:9000"
    links:
      - influxdb
    environment:
      INFLUX_HOST: influxdb
    command: "npm start"
  grafana:
    image: grafana/grafana:latest
    ports:
     - "3000:3000"
    volumes:
      - ../../../data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      GF_SERVER_ROOT_URL: http://localhost